from django.urls import path
from . import views

urlpatterns = [
    path('login/',views.adminLogin,name='adminLogin'),
    path('dashboard/',views.adminDashboard,name='adminDashboard'),
    path('logout/', views.adminLogout, name='adminLogout'),
    path('dashboard/<slug:month>', views.adminDashboardMonthwise,name='adminDashboardMonthwise'),
    path('admin_messages',views.adminMessages,name='adminMessages'),
    path('delete_message/<int:id>',views.deleteMessage,name='deleteMessage'),
    path('reply_message',views.replyMessage,name='replyMessage'),
    # path('admin_blog',views.admin_blog,name='admin_blog'),
    # path('add_blog',views.add_blog,name='add_blog'),
    # path('delete_blog/<int:id>',views.delete_blog,name='delete_blog'),
    # path('edit_blog/<int:id>',views.edit_blog,name='edit_blog'),
    # path('edit_blog_single/<int:id>',views.edit_blog_single,name='edit_blog_single'),
    path('admin_user_management',views.adminUserManagement,name='adminUserManagement'),
    path('<int:id>/edit_user_data/', views.editUserData, name='editUserData'),
    path('<int:id>/block_user/', views.blockUser, name='blockUser'),
    path('admin_categories',views.adminCategories,name='adminCategories'),
    path('<str:category_slug>/edit_category',views.adminEditCategory,name='adminEditCategory'),
    path('<str:category_slug>/delete_category',views.adminDeleteCategory,name='adminDeleteCategory'),
    path('add_category',views.adminAddCategory,name='adminAddCategory'),
    path('category_offers/', views.categoryOffers, name='categoryOffers'),
    path('add_category_offer/', views.addCategoryOffer, name='addCategoryOffer'),
    path('delete_category_offer/<int:id>/', views.deleteCategoryOffer, name='deleteCategoryOffer'),
    path('<str:category_slug>/subcategories/', views.subCategories, name='adminSubcategories'),
    path('<str:category_slug>/add_subcategory/', views.addSubcategory, name='adminAddSubCategory'),
    path('<str:slug>/edit_subcategory/', views.editSubcategory, name='editSubcategory'),
    path('<str:slug>/delete_subcategory/', views.deleteSubcategory, name='deleteSubcategory'),
    path('admin_products/', views.adminProducts, name='adminProducts'),
    path('<int:id>/admin_delete_product/', views.adminDeleteProduct, name='adminDeleteProduct'),
    path('<int:id>/admin_edit_product/', views.adminEditProduct, name='adminEditProduct'),
    path('admin_add_product/', views.adminAddProduct, name='adminAddProduct'),
    path('admin_product_offers/', views.adminProductOffers, name='adminProductOffers'),
    path('add_product_offer/', views.addProductOffer, name='addProductOffer'),
    path('delete_product_offer/<int:id>/', views.deleteProductOffer, name='deleteProductOffer'),
    path('admin_orders/', views.adminOrders, name='adminOrders'),
    path('admin_change_order/<int:id>',views.adminChangeOrder,name="adminChangeOrder"),
    path('admin_coupons/',views.adminCoupons,name="adminCoupons"),
    path('admin_add_coupon/',views.adminAddCoupon,name="adminAddCoupon"),
    path('admin_edit_coupon/<int:id>/',views.adminEditCoupon,name="adminEditCoupon"),
    path('admin_delete_coupon/<int:id>/',views.adminDeleteCoupon,name="adminDeleteCoupon"),
    path('admin_sales_data',views.adminSalesData,name='adminSalesData'),
    # path('monthwise_sales/<int:id>',views.monthwise_sales,name='monthwise_sales'),
    # path('yearwise_sales/<int:id>',views.yearwise_sales,name='yearwise_sales'),
    
]